### PR TITLE
closes #9. Feature 9 model improvements

### LINKED ISSUE #9: Backend model improvements
1) Add validations to model according to DB model (see javax.validation.constraints annotations).
2) This messages should be propagated to error response including fields that constraints was failed (info will be available in exception).
3) Remove @Column if column name matches field name (it's redundant).
4) Delete unused methods.
Can be updated later.

### PR DESCRIPTION
**Pull request by TomSuworof**
Backend: Removed unnecessary annotations, added validations, api/containers -> payload/response (makes more sense). Frontend: Added axios' interceptor for handling token expiration

### CODE REVIEW

File: backend/src/main/java/com/salat/briene/payload/response/ArticleContainer.java [hunk 1]
```diff
@@ -0,0 +1,22 @@
+package com.salat.briene.payload.response;
+
+import com.salat.briene.entities.Article;
+import lombok.Getter;
+
+import java.util.Date;
+
+@Getter
+public abstract class ArticleContainer {
```
Comment (Maxitet) [inline backend/src/main/java/com/salat/briene/payload/response/ArticleContainer.java:9]: Rename container classes to DTO's

File: backend/src/main/java/com/salat/briene/api/ApiAdminController.java [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+
+import java.util.List;
+import java.util.stream.Collectors;
+
+@CrossOrigin(origins = "http://localhost:8081")
+@RestController
+@RequestMapping("/api/admin")
+@PreAuthorize("hasRole('ADMIN')")
+@RequiredArgsConstructor
+public class ApiAdminController {
```
Comment (Maxitet) [inline backend/src/main/java/com/salat/briene/api/ApiAdminController.java:23]: Remove Api from controllers class name
