### PR TITLE
closes #8. Feature 8 exception handling

### LINKED ISSUE #8: Generalize exception handling
After migration to Vue frontend need to generalize exceptions and exception handling. Exceptions should be handled in places where it'll make most sense. As much close to cause as it possible. 
1) Check Spring's @ControllerAdvice. It'll help to map exception to response.
2) Create error message model (class or group of classes). It can contain error message and error code(-s) that will be returned from backend.

### PR DESCRIPTION
**Pull request by TomSuworof**

### CODE REVIEW

File: backend/src/main/java/com/salat/briene/controlleradvices/UserAdvice.java [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+    @ExceptionHandler(AnonymousUserException.class)
+    public ResponseEntity<?> handleAnonymousUser(AnonymousUserException e) {
+        e.printStackTrace();
+        return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(e.getMessage());
+    }
+
+    @ExceptionHandler(DuplicatedUserException.class)
+    public ResponseEntity<?> handleDuplicatedUser(DuplicatedUserException e) {
+        e.printStackTrace();
+        return ResponseEntity.status(HttpStatus.SEE_OTHER).body(e.getMessage());
```
Comment (Maxitet) [inline backend/src/main/java/com/salat/briene/controlleradvices/UserAdvice.java:22]: I think **422 Unprocessable Entity** will be more accurate here. 303 should be used if we redirecting to already created entity. But it's not our case. 422 code means that request was understood by server, but it can't be served for some logical reason.

File: backend/src/main/java/com/salat/briene/controlleradvices/UserAdvice.java [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+public class UserAdvice {
+    @ExceptionHandler(AnonymousUserException.class)
+    public ResponseEntity<?> handleAnonymousUser(AnonymousUserException e) {
+        e.printStackTrace();
+        return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(e.getMessage());
+    }
+
+    @ExceptionHandler(DuplicatedUserException.class)
+    public ResponseEntity<?> handleDuplicatedUser(DuplicatedUserException e) {
+        e.printStackTrace();
```
Comment (Maxitet) [inline backend/src/main/java/com/salat/briene/controlleradvices/UserAdvice.java:21]: 1) We just print this exception to console (without timestamp, thread, class,) - it's not the right way for logging. We always need to use loggers (slf4j for example)
2) Do we need to log this errors? It's not application, but user-side error. We can log them, but on debug level in my opinion.

**Comment by Maxitet** [comment]
Add error class with message and optional list of errors. Serialize it to json.
