### PR TITLE
closes #20. Feature 20 backend code quality

### LINKED ISSUE #20: Backend code quality impovements
1) Use constants (enum or interface or class-level, what seems more reasonable in each case). There should be no string literals without declared variables.
2) Delete flyway.properties from root dir
3) Add missing flyway-core dependency
4) We don't store timezone, which will lead to incorrect dates for users. Use OffsetDateTime in backend and timestampz in DB.
5) Use UUID as id instead of objects hashcode.

### PR DESCRIPTION
**Pull request by TomSuworof**

### CODE REVIEW

File: backend/src/main/java/com/salat/briene/entities/ArticleState.java [hunk 1]
```diff
@@ -1,5 +1,34 @@
...
+    PUBLISHED("published", "publish"),
+    IN_EDITING("drafts", "save"),
+    ALL("all", null);
+
+    private String description;
+
+    private String actionForThisState;
+
+    public static ArticleState getFromDescription(String description) throws IllegalArticleStateException {
+        return switch (description.toLowerCase()) {
```
Comment (Maxitet) [inline backend/src/main/java/com/salat/briene/entities/ArticleState.java:19]: FYI: you can iterate through enum values and try find match, so you won't need to update this method on enum update. We can't forget to do it later, and it's also easier to read (we see match of  description - method argument and same enum value).

File: backend/src/main/java/com/salat/briene/exceptions/ArticleNotFoundException.java [hunk 2]
```diff
@@ -3,17 +3,17 @@
 import java.io.IOException;
 
 public class ArticleNotFoundException extends IOException {
```
Comment (Maxitet) [inline backend/src/main/java/com/salat/briene/exceptions/ArticleNotFoundException.java:5]: We have a lot of checked exceptions and also a lot of propagations. For me, IOException is more system-level and shouldn't be triggered by user actions. We can extend from RuntimeException because we handling exceptions in ControllerAdvices.

File: backend/src/main/java/com/salat/briene/controllers/ArticlesController.java [hunk 3]
```diff
@@ -101,21 +104,21 @@ private ArticleDTO getArticleRaw(Long id, Authentication authentication) throws
             @RequestParam String content,
             @RequestParam(required = false) String summary,
             @RequestParam String action,
-            Authentication authentication) throws DuplicatedArticleException, AnonymousUserException {
+            Authentication authentication) throws DuplicatedArticleException, AnonymousUserException, IllegalArticleStateException {
         User userFromToken = userService.getUserFromAuthentication(authentication);
         articleEditorService.loadArticle(userFromToken, title, content, summary, action);
```
[the remark this answers is not in the document]
Comment (TomSuworof) [reply backend/src/main/java/com/salat/briene/controllers/ArticlesController.java]: loadArticle can either "save" and "publish" article, but name "saveArticle" suggests that method can only "save" article. Maybe uploadArticle?
